#!/usr/bin/env python3 
device_list = {
        'Brother': ['Brother Industries, Ltd.'],
        'HewlettPackard': ['HP Color LaserJet'],
        'Motorola': ['Motorola'],
        'Eaton': ['Network Management Card'],
        'Polycom': ['Polycom'],
        'Microsoft': ['microsoft.com'],
        'Canonical': ['Ubuntu'],
        'Linksys': ['Sipura'],
        'Cisco': ['cisco', 'Cisco'],
        'Cisco Codec': ['Cisco Codec'],
        'APC': ['APC | Log On'],
        'Sony': ['Sony', 'Sony Network Camera'],
        'Apple': ['OS X Server'],
        'nginx': ['nginx'],
        'Weather Observation': ['Observation', 'Precipitation', 'Indoor Temperature'],
        'i-Vu (ICS)': ['Login Page', 'i-Vu CCN Log in'],
        'Trango': ['Trango'],
        'iWorx': ['lci2'],
        'Microtik': ['RouterOS'],
        'Sharp': ['sharp-world.com'],
        'Oracle': ['Oracle'],
        'Tomcat': ['Apache Tomcat'],
        'Emerson': ['Liebert IntelliSlot Web Card'],
        'FreePBX': ['FreePBX'],
}
